apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-jenkins
  labels:
    app: ktor-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ktor-jenkins
  template:
    metadata:
      labels:
        app: ktor-jenkins
    spec:
      containers:
      - name: ktor-jenkins
        image: t3ddblair/ktor-jenkins:latest
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: ktor-jenkins-service
spec:
  selector:
    app: ktor-jenkins
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
